StatPop/Models/ErrorViewModel.cs
using System;

namespace StatPop.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

StatPop/Models/Pays.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ApiPopStat.Models
{
    public class Pays
    {
        public int id { get; set; }
        public string Country_Name { get; set; }
        public string Country_Code { get; set; }
        public string Region { get; set; }
        public string Income_Group { get; set; }

        public Pays()
        {

        }
    }
}

StatPop/Models/Population.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ApiPopStat.Models
{
    public class Population
    {
        public int id { get; set; }
        public string Country_Name { get; set; }
        public string Country_Code { get; set; }
        public string Indicator_Name { get; set; }
        public string Indicator_Code { get; set; }
        public List<double> Years { get; set; }
        public List<int> annee { get; set; }
        public Population()
        {
            this.Years = new List<double>();
        }
    }
}

StatPop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using StatPop.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace StatPop.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

StatPop/Controllers/PaysController.cs
using ApiPopStat.Models;
using Microsoft.AspNetCore.Mvc;
using StatPop.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StatPop.Controllers
{
    public class PaysControllers : Controller
    {
        public IActionResult IndexAsync()
        {
            //return View(await _context.Country.Include("Links").ToListAsync());

            List<Pays> countries = (List<Pays>)PaysAPI.Instance.GetAllPays().Result;
            //ViewBag.liste_pays = countries;
           
            return View(countries);
        }

    }
}

StatPop/Controllers/PopulationController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using StatPop.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ApiPopStat.Models;

namespace StatPop.Controllers
{
    public class PopulationController : Controller
    {
        public IActionResult liste_name_pays()
        {
            
            List<Population> PopulationAllName = (List<Population>)PopulationAPI.Instance.GetPopulationAllName().Result;
            
            return View(PopulationAllName);
        }
        public IActionResult Details(int id)
        {
            List<int> anne= new List<int>();

            for (var i = 1961; i < 2020; i++)
            {
                anne.Add(i);
    }

            Population PopulationAllYears = (Population)PopulationAPI.Instance.GetPopulationAllYears(id).Result;
            PopulationAllYears.annee = anne;
            @ViewBag.single_population = PopulationAllYears;
            return View();
        }
        public IActionResult graphe(int id)
        {
           
            Population PopulationAllYears = (Population)PopulationAPI.Instance.GetPopulationAllYears(id).Result;
            List<int> List_date = new List<int>();
            string json1 = JsonConvert.SerializeObject(PopulationAllYears.Years);
            ViewBag.liste_years = json1;
            for (var i = 1962; i <= 2020; i++)
            {
                List_date.Add(i);
            }
            string json3 = JsonConvert.SerializeObject(List_date);
            ViewBag.liste_anne = json3;
            @ViewBag.single_population = PopulationAllYears;
            return View();
        }
        public IActionResult population_5ans(int id)
        {

            Population PopulationAllYears = (Population)PopulationAPI.Instance.GetPopulationOn5Async(id).Result;
            List<int> List_date = new List<int>();
            string json1 = JsonConvert.SerializeObject(PopulationAllYears.Years);
            ViewBag.liste_years = json1;
            for (var i = 2015; i <= 2020; i++)
            {
                List_date.Add(i);
            }
            string json3 = JsonConvert.SerializeObject(List_date);
            ViewBag.liste_anne = json3;
            @ViewBag.single_population = PopulationAllYears;
            return View();
        }
        public IActionResult population_10ans(int id)
        {

            Population PopulationAllYears = (Population)PopulationAPI.Instance.GetPopulationOn10Async(id).Result;
            List<int> List_date = new List<int>();
            string json1 = JsonConvert.SerializeObject(PopulationAllYears.Years);
            ViewBag.liste_years = json1;
            for (var i = 2010; i <= 2020; i++)
            {
                List_date.Add(i);
            }
            string json3 = JsonConvert.SerializeObject(List_date);
            ViewBag.liste_anne = json3;
            @ViewBag.single_population = PopulationAllYears;
            return View();
        }
        public IActionResult population_20ans(int id)
        {

            Population PopulationAllYears = (Population)PopulationAPI.Instance.GetPopulationOn20Async(id).Result;
            List<int> List_date = new List<int>();
            string json1 = JsonConvert.SerializeObject(PopulationAllYears.Years);
            ViewBag.liste_years = json1;
            for (var i = 2000; i <= 2020; i++)
            {
                List_date.Add(i);
            }
            string json3 = JsonConvert.SerializeObject(List_date);
            ViewBag.liste_anne = json3;
            @ViewBag.single_population = PopulationAllYears;
            return View();
        }
        public IActionResult population_30ans(int id)
        {

            Population PopulationAllYears = (Population)PopulationAPI.Instance.GetPopulationOn30Async(id).Result;
            List<int> List_date = new List<int>();
            string json1 = JsonConvert.SerializeObject(PopulationAllYears.Years);
            ViewBag.liste_years = json1;
            for (var i = 1990; i <= 2020; i++)
            {
                List_date.Add(i);
            }
            string json3 = JsonConvert.SerializeObject(List_date);
            ViewBag.liste_anne = json3;
            @ViewBag.single_population = PopulationAllYears;
            return View();
        }
        public IActionResult population_40ans(int id)
        {

            Population PopulationAllYears = (Population)PopulationAPI.Instance.GetPopulationOn40Async(id).Result;
            List<int> List_date = new List<int>();
            string json1 = JsonConvert.SerializeObject(PopulationAllYears.Years);
            ViewBag.liste_years = json1;
            for (var i = 1980; i <= 2020; i++)
            {
                List_date.Add(i);
            }
            string json3 = JsonConvert.SerializeObject(List_date);
            ViewBag.liste_anne = json3;
            @ViewBag.single_population = PopulationAllYears;
            return View();
        }
        public IActionResult population_50ans(int id)
        {

            Population PopulationAllYears = (Population)PopulationAPI.Instance.GetPopulationOn50Async(id).Result;
            List<int> List_date = new List<int>();
            string json1 = JsonConvert.SerializeObject(PopulationAllYears.Years);
            ViewBag.liste_years = json1;
            for (var i = 1970; i <= 2020; i++)
            {
                List_date.Add(i);
            }
            string json3 = JsonConvert.SerializeObject(List_date);
            ViewBag.liste_anne = json3;
            @ViewBag.single_population = PopulationAllYears;
            return View();
        }
    }
}

StatPop/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

StatPop/Views/Pays/DashBoard.cshtml
@{
    ViewData["Title"] = "DashBoard";
}

<div class=" contenair-fluid section1 text-center ">
    <h1>DashBoard</h1>
</div>
<div class=" row container-fluid section1 text-center">
    <div class="col-md-6 mb-3">
        <h2>caractéristique du graphe</h2>
    </div>
    <div class="col-md-6 mb-3">
        <canvas id="myChart" width="400" height="400"></canvas>
    </div>
</div>
    <script>
    var ctx = document.getElementById('myChart').getContext('2d');
    var v = @Html.Raw(@ViewBag.income);
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels:v,
        datasets: [{
            label: '# of Votes',
            data: @ViewBag.count_income ,
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
    </script>

StatPop/Views/Pays/Details.cshtml
@model ApiPopStat.Models.Pays

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Pays</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country_Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country_Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country_Code)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country_Code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Region)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Region)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Income_Group)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Income_Group)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

StatPop/Views/Pays/Edit.cshtml
@model ApiPopStat.Models.Pays

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Pays</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="Country_Name" class="control-label"></label>
                <input asp-for="Country_Name" class="form-control" />
                <span asp-validation-for="Country_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country_Code" class="control-label"></label>
                <input asp-for="Country_Code" class="form-control" />
                <span asp-validation-for="Country_Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Region" class="control-label"></label>
                <input asp-for="Region" class="form-control" />
                <span asp-validation-for="Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Income_Group" class="control-label"></label>
                <input asp-for="Income_Group" class="form-control" />
                <span asp-validation-for="Income_Group" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

StatPop/Views/Pays/GetData.cshtml
@model IEnumerable<ApiPopStat.Models.Pays>

@{
    ViewData["Title"] = "GetData";
}

<h1>GetData</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Country_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country_Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Region)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Income_Group)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Country_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country_Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Region)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Income_Group)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                <a asp-action="Details"  asp-route-id="@item.id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

StatPop/Views/Pays/Index.cshtml
@{
    ViewData["Title"] = "Index";
}


<div class=" contenair-fluid section1 text-center ">
    <h1>Bienvenue</h1>
    <div class="row container-fluid section1 text-center">
        <div class="col-md-6 col-12  container-fluid mb-4 ">
            <br>
            <br>
            <br>
            <br>
            <a asp-action="index1"><h2 class="my-4 mb-5 text-uppercase shadow-lg p-3 text-center film mb-5 bg-white rounded "> <span class="badge badge-white">Fichier 1 </span></h2></a>

            <p class=" text-center text-uppercase  text-black commentaires">
                souhaitez vous travailler avec les données du fichier metadata country
            </p>
        </div>
        <div class="col-md-6 col-12  container-fluid mb-4 ">
            <br>
            <br>
            <br>
            <br>
            <a asp-action="Index" asp-controller="Population"><h2 class="my-4 mb-5 text-uppercase shadow-lg p-3 text-center film mb-5 bg-white rounded "> <span class="badge badge-white">Fichier 2 </span></h2></a>

            <p class=" text-center text-uppercase  text-black commentaires">
                souhaitez vous travailler avec les données du fichier Indicateurs du développement dans le monde
            </p>
        </div>
    </div>

</div>

StatPop/Views/Pays/Index1.cshtml
@model IEnumerable<ApiPopStat.Models.Pays>

@{
    ViewData["Title"] = "Index1";
}

<div class=" contenair-fluid section1 text-center ">
    <h1>Données du fichier</h1>
</div>
<p>
    <a asp-action="Create">Create New</a>
</p>
<p>
    <a asp-action="DashBoard">graphe des incomes</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Country_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country_Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Region)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Income_Group)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Country_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Country_Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Region)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Income_Group)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

StatPop/Views/Pays/PaysForm.cshtml
@model ApiPopStat.Models.Pays

@{
    ViewData["Title"] = "PaysForm";
}

<h1>PaysForm</h1>
@using (Html.BeginForm("ProcessCreate", "Pays"))
{
    @Html.AntiForgeryToken()
<h4>Pays</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="PaysForm">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Country_Name" class="control-label"></label>
                <input asp-for="Country_Name" class="form-control" />
                <span asp-validation-for="Country_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country_Code" class="control-label"></label>
                <input asp-for="Country_Code" class="form-control" />
                <span asp-validation-for="Country_Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Region" class="control-label"></label>
                <input asp-for="Region" class="form-control" />
                <span asp-validation-for="Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Income_Group" class="control-label"></label>
                <input asp-for="Income_Group" class="form-control" />
                <span asp-validation-for="Income_Group" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
}

StatPop/Views/Pays/test.cshtml
@model IEnumerable<ApiPopStat.Models.Pays>

@{
    ViewData["Title"] = "test";
}

<h1>test</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country_Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Region)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Income_Group)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country_Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Region)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Income_Group)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

StatPop/Views/Population/Details.cshtml
@model ApiPopStat.Models.Population

@{
    ViewData["Title"] = "Details";
}


<div class=" contenair-fluid section1 text-center ">
    <h1>@ViewBag.single_population.Country_Name</h1>
</div>
<div class=" contenair-fluid section1 text-center ">
    <div class="row container-fluid section1 text-center">
        <div class="col-md-2 col-12  container-fluid mb-4 ">
            <a asp-action="Population_50ans" asp-controller="Population" asp-route-id="@ViewBag.single_population.id"><p class="my-4  text-uppercase shadow-sm text-center bg-white rounded "> <span class="badge badge-white">On 50 last years</span></p></a>

        </div>
        <div class="col-md-2 col-12  container-fluid mb-4 ">
            <a asp-action="Population_40ans" asp-controller="Population" asp-route-id="@ViewBag.single_population.id"><p class="my-4  text-uppercase shadow-sm text-center bg-white rounded "> <span class="badge badge-white">On 40 last years</span></p></a>

        </div>
        <div class="col-md-2 col-12  container-fluid mb-4 ">
            <a asp-action="Population_30ans" asp-controller="Population" asp-route-id="@ViewBag.single_population.id"><p class="my-4  text-uppercase shadow-sm text-center bg-white rounded "> <span class="badge badge-white">On 30 last years</span></p></a>

        </div>
        <div class="col-md-2 col-12  container-fluid mb-4 ">
            <a asp-action="Population_20ans" asp-controller="Population" asp-route-id="@ViewBag.single_population.id"><p class="my-4  text-uppercase shadow-sm text-center bg-white rounded "> <span class="badge badge-white">On 20 last years</span></p></a>

        </div>
        <div class="col-md-2 col-12  container-fluid mb-4 ">
            <a asp-action="Population_10ans" asp-controller="Population" asp-route-id="@ViewBag.single_population.id"><p class="my-4  text-uppercase shadow-sm text-center bg-white rounded "> <span class="badge badge-white">On 10 last years</span></p></a>

        </div>
        <div class="col-md-2 col-12  container-fluid mb-4 ">

            <a asp-action="Population_5ans" asp-controller="Population" asp-route-id="@ViewBag.single_population.id"><p class="my-4  text-uppercase shadow-sm text-center bg-white rounded "> <span class="badge badge-white">On 5 last years</span></p></a>

        </div>
        <div class="col-md-2 col-12  container-fluid mb-4 ">

            <a asp-action="graphe" asp-controller="Population" asp-route-id="@ViewBag.single_population.id"><p class="my-4  text-uppercase shadow-sm text-center bg-white rounded "> <span class="badge badge-white">All years</span></p></a>

        </div>
    </div>

</div>
<div class="row container-fluid section1 text-center">

    <div class="col-md-6 col-12  container-fluid mb-4 " >
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Année
                    </th>
                </tr>
            </thead>
            <tbody>
                @for (var i = 1961; i < 2020; i++)
                {
                    <tr>
                        <td>
                            @i
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="col-md-6 col-12  container-fluid mb-4 ">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Croissance
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var year in @ViewBag.single_population.Years)
                {
                    <tr>
                        <td>
                            @year
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</div>

StatPop/Views/Population/graphe.cshtml
+

@{
    ViewData["Title"] = "Index";
}

<div class=" contenair-fluid section1 text-center ">
    <h1>Graphe variation croissance</h1>
</div>
<div class=" row container-fluid section1 text-center">
    <div class="col-md-12 text-center mb-3">
        <h2>caractéristique du graphe</h2>
        <p>Variation de la croissance de la population suivant toutes les années </p>
    </div>
</div>
<div class="row container-fluid section1 text-center">
    <div class="col-md-2">

    </div>
    <div class="col-md-8 mb-3">
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <canvas id="myChart" width="500" height="500"></canvas>
    </div>
    <div class="col-md-2">

    </div>
</div>
<script>
    var ctx = document.getElementById('myChart').getContext('2d');
    var v = @Html.Raw(@ViewBag.liste_years);
    var ctx = document.getElementById('myChart').getContext('2d');
    var chart = new Chart(ctx, {
        // The type of chart we want to create
        type: 'line',

        // The data for our dataset
        data: {
            labels: @ViewBag.liste_anne ,
            datasets: [{
                label: 'Population croissance per year',
                backgroundColor: 'rgb(255, 99, 132)',
                borderColor: 'rgb(255, 99, 132)',
                data: @ViewBag.liste_years
            }]
        },

        // Configuration options go here
        options: {}
    });
</script>

StatPop/Views/Population/index_population.cshtml
@{
    ViewData["Title"] = "index";
}

<div class=" contenair-fluid section1 text-center ">
    <h1>Données du fichier</h1>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                Country Name
            </th>
            <th>
                informations supplémentaires sur le pays
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in ViewBag.liste_name)
        {
        <tr>
            
            <td>
                @item.Country_Name
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.id">Détails</a>
            </td>
        </tr>
        }
    </tbody>
</table>

StatPop/Views/Population/liste_name_pays.cshtml
@model IEnumerable<ApiPopStat.Models.Population>

@{
    ViewData["Title"] = "liste_name_pays";
}


<div class="col-md-12 mb-3">
    <div class=" row container-fluid section1 text-center">

    </div>
</div>
<div class=" contenair-fluid section1 text-center ">
    <h1>Liste des pays</h1>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Country_Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Country_Name)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.id">Détails</a>
                </td>
            </tr>
        }
    </tbody>
</table>

StatPop/Views/Population/population_10ans.cshtml
@{
    ViewData["Title"] = "population sur 5 ans";
}

<div class=" contenair-fluid section1 text-center ">
    <h1>Graphe de variation croissance</h1>
</div>
<div class=" row container-fluid section1 text-center">
    <div class="col-md-12 text-center mb-3">
        <h2>caractéristique du graphe</h2>
        <p>Variation de la croissance de la population suivant toutes les années </p>
    </div>
</div>
<div class="row container-fluid section1 text-center">
    <div class="col-md-2">

    </div>
    <div class="col-md-8 mb-3">
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <canvas id="myChart" width="500" height="500"></canvas>
    </div>
    <div class="col-md-2">

    </div>
</div>
<script>
    var ctx = document.getElementById('myChart').getContext('2d');
    var v = @Html.Raw(@ViewBag.liste_years);
    var ctx = document.getElementById('myChart').getContext('2d');
    var chart = new Chart(ctx, {
        // The type of chart we want to create
        type: 'line',

        // The data for our dataset
        data: {
            labels: @ViewBag.liste_anne ,
            datasets: [{
                label: 'Population croissance per year',
                backgroundColor: 'rgb(255, 99, 132)',
                borderColor: 'rgb(255, 99, 132)',
                data: @ViewBag.liste_years
            }]
        },

        // Configuration options go here
        options: {}
    });
</script>

StatPop/Views/testController1/Index.cshtml
@{
    ViewData["Title"] = "Index";
}


<div class=" contenair-fluid section1 text-center ">
    <h1>Bienvenue</h1>
    <div class="row container-fluid section1 text-center">
        <div class="col-md-6 col-12  container-fluid mb-4 ">
            <br>
            <br>
            <br>
            <br>
            <a asp-action="liste_pays"><h2 class="my-4 mb-5 text-uppercase shadow-lg p-3 text-center film mb-5 bg-white rounded "> <span class="badge badge-white">Fichier 1 </span></h2></a>

            <p class=" text-center text-uppercase  text-black commentaires">
                souhaitez vous travailler avec les données du fichier metadata country
            </p>
        </div>
        <div class="col-md-6 col-12  container-fluid mb-4 ">
            <br>
            <br>
            <br>
            <br>
            <a asp-action="liste_name_pays" asp-controller="Population"><h2 class="my-4 mb-5 text-uppercase shadow-lg p-3 text-center film mb-5 bg-white rounded "> <span class="badge badge-white">Fichier 2 </span></h2></a>

            <p class=" text-center text-uppercase  text-black commentaires">
                souhaitez vous travailler avec les données du fichier Indicateurs du développement dans le monde
            </p>
        </div>
    </div>

</div>